### ISSUE TITLE
Invite user to Discord after 10 usages

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord-vscode#114]

**Comment by gememma** [comment]
I used a similar setup to the dialogue that prompts for user feedback, it looks like this: 
![Screenshot 2024-05-16 at 18 13 54](https://github.com/metalbear-co/mirrord-vscode/assets/58080601/8413cb52-04b3-4738-a563-055010a316fc)
@eyalb181 what do you think?

**Comment by eyalb181** [comment]
I'd rather not bring the "backend community" concept in at this point and keep the message focused on mirrord. How about:

"Need any help with mirrord? Come chat with our team on Discord!"
