### ISSUE TITLE
Write toggle status to disk

### ISSUE THREAD

**Issue by drehelis** [metalbear-co/mirrord-vscode#129]
[Deprecation of the pause feature](https://metalbear.co/blog/on-pausing-containers-how-we-built-and-why-we-deprecated-our-container-pause-feature/) forces us to manipulate remote workload to suite well with the `steal` mechanism of mirrord.

Utilizing vscode's `preLaunchTask` & `postDebugTask` in `launch.json` makes it possible to execute relevant logic that can help in accomplishing the above.

Since pre/post launch is not running in mirrord's context, my ask is to add toggle status as a form of file on disk, which can be parsed and execute he relevant logic.

Currently this only dumps the toggle status but can be extended with additional data that might be relevant in the future.

Implemented in https://github.com/metalbear-co/mirrord-vscode/pull/128

**Comment by eyalb181** [comment]
Hey Danny, we'd rather not add another API that we'd need to maintain, especially since the pause functionality is currently supported in mirrord for Teams. If we see a more generalized (and more popular) requirement for this feature we'll consider prioritizing it.
