### ISSUE TITLE
VS Code Node debugger crashes

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord-vscode#2]
### Bug Description

When debugging a Node process with mirrord enabled (no matter which features are turned on), I get the attached crash.
<img width="258" alt="Screenshot 2022-09-07 at 22 38 23" src="https://user-images.githubusercontent.com/5508354/188962902-3d3eab0e-3ca7-44fd-93cc-2059c0c203c8.png">

When adding the runtimeExecutable env var as suggested, it works, but then breakpoints are grayed out like so:
<img width="543" alt="Screenshot 2022-09-07 at 22 45 28" src="https://user-images.githubusercontent.com/5508354/188963836-4ecf0e2d-2ea8-4d38-b04d-b58c2aa93852.png">

### Steps to Reproduce

Debug a Node process in VS Code with mirrord enabled.

### Relevant Logs

```{"type":"NewTask","name":"waiting for pod to be ready...","parent":"mirrord preparing to launch"}

extensionHostProcess.js:105
mirrord stderr: 2023-06-15T07:51:18.250399Z ERROR kube_client::client::builder: failed with status 500 Internal Server Error

extensionHostProcess.js:105
mirrord: {"type":"FinishedTask","name":"waiting for pod to be ready...","success":true,"message":"pod is ready"}
```
### Your operating system and version

MacOS M1

### Local process

node

### Workaround

Set runtimeExecutable like it suggests, then everything works.

**Comment by aviramha** [comment]
@eyalb181 does it still happen?

**Comment by eyalb181** [comment]
Yup

**Comment by aviramha** [comment]
Fixed by https://github.com/metalbear-co/mirrord/pull/2872
