### ISSUE TITLE
nvm use - doesn't get SIP patched(?)

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-vscode#34]
macOS
similar to https://github.com/metalbear-co/mirrord-vscode/issues/26 
launch.json 
```json
{
      "command": "nvm use; npm run build:prod",
      "name": "Run npm start",
      "request": "launch",
      "type": "node-terminal"
 }
```

**Comment by t4lz** [comment]
Yup, didn't handle a multi-command line, so we would only patch `nvm` in with this command line.
I guess we need some more sophisticated logic that detects which word out of multiple words in multiple`;`-seperated commands is the relevant node executable.

**Comment by t4lz** [comment]
> > Yup, didn't handle a multi-command line, so we would only patch `nvm` in with this command line. I guess we need some more sophisticated logic that detects which word out of multiple words in multiple`;`-seperated commands is the relevant node executable.
> 
> what about just wrapping it all in a shell so we patch the shell, then on exec/fork we already handle it from there?

Smart!
