### ISSUE TITLE
zsh not supported with `node-terminal`

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-vscode#40]
Follow up after #37 #34 
When zsh is being used we get 
```
/Users/user/.oh-my-zsh/oh-my-zsh.sh:56: read failed: is a directory
compinit:480: compdump: function definition file not found
```

**Comment by eyalb181** [comment]
@t4lz We think this might have been resolved, could you retest?

**Comment by t4lz** [comment]
> @t4lz We think this might have been resolved, could you retest?

Ran with mirrord, with zsh as shell and with this launch configuration:

```json
        {
            "command": "nvm use; npm run dotenv-cli",
            "name": "npm dotenv-cli",
            "request": "launch",
            "type": "node-terminal",
            "env": {
                "MIRRORD_AGENT_RUST_LOG": "mirrord=trace",
                "RUST_LOG": "warn,mirrord=error"
            }
        }
 ```

And didn't get that error. There are no reproduction instructions though, so I can't be sure this would reproduce with this setup.

**Comment by aviramha** [comment]
Thank u!
