### ISSUE TITLE
Kube context cluster name with spaces cannot be connected to

### ISSUE THREAD

**Issue by alexbowers** [metalbear-co/mirrord-vscode#83]
### Bug Description

If you have your kubernetes cluster context with a name with a space: eg. `Staging Cluster`, then you are unable to switch to the cluster in VScode:

The error reported:

```
Failed to switch the namespace: error: Unexpected args: [Staging Cluster]

```

If I change the name to `staging-cluster` in the kube config, then connecting works.

### Steps to Reproduce

1. Create a cluster and make sure that the name has a space in the kube config.
2. Try to switch the namespace and / or the cluster.

### Your operating system and version

Mac OS latest

### Local process

.

**Comment by aviramha** [comment]
Hey @alexbowers - thanks for reporting this. Can you share a screenshot how you're doing this? I don't think it's a feature that's part of our extension (rather feature of the VSCode k8s extension 😄 )

**Comment by aviramha** [comment]
Hey @alexbowers - please let me know if it's still relevant.
